### ISSUE TITLE
need update and change port

### ISSUE THREAD

**Issue by cocodrino** [twitter/finatra-activator-seed#1]
Hi, I notice 2 problems with the activator, the latest finatra is 2.0.0.M3 and this activator is using M2..and the ports..activator use the same port 8888 than the activator, that means, you can run finatra inside the activator, at least, not changing the ports before, thanks!!

**Comment by cacoco** [comment]
The latest published Finatra is 2.0.0.M2. Version 2.0.0.M3-SNAPSHOT has not yet been released/published, thus the activator template uses what is available.

As for the port, I'll document the need to run using a port different than the default of :8888 -- thanks!

**Comment by cacoco** [comment]
Updated README.md and tutorial.
